server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vijayshinde2023/smartorder-config
          default-label: main
          clone-on-start: true
